### ISSUE TITLE
bug(): series icon svg image won't render

### ISSUE THREAD

**Issue by eduardoRoth** [leocabeza/smashbros-api#1]
`series.icon` `svg` images won't render in an `img` tag.

![image](https://github.com/user-attachments/assets/fbf3e612-adeb-48df-a7ee-04dac21a6ee8)

**Comment by eduardoRoth** [comment]
Response Content-Type shows `application/xml` instead of `image/svg+xml`

**Comment by leocabeza** [comment]
Thank you for reporting this.

This was fixed in cloudlflare, since it seems like a cloud storage bug with webp and svg files.
